import os
import openai
import json
import ast


from dotenv import load_dotenv

load_dotenv('.env')

openai.api_key = os.environ.get("API_KEY")


def getTaskList(doc: str, start: str, end: str) -> list:
  """Turns the text of a assignment doc into a timeline of tasks for it

  Args:
      doc (str): text from the document
      start (str): start date
      end (str): end date

  Returns:
      (list): a list of sub tasks 
  """
  prompt = f"""
  Assuming the start date is {start}, and the final deadline is {end}, generate a general timeline with recommended deadlines for each task in the following text delimited by three backticks. Add a description and Not Started status for each task and structure the output as a python list of dictionary. The format of the JSON should be the exact same as the example delimited by three single quotation marks. REMEMBER: You should only copy the format of the example and output as JSON file; the content should be generated by yourself, based on the provided input.
  '''
  {[{
    'Task': 'Create Figma UI Design',
    'Description': 'Create the UI using Figma of the website',
    'Status': 'Not Started',
    'Deadline': 'Nov. 30, 2023'
  }]}
  '''
"""


  text = f"{prompt}\n```\n{doc}\n```"

  completion = openai.ChatCompletion.create(
    model="gpt-3.5-turbo",
    messages=[
        {"role": "user", "content": text}
    ],
    temperature=0
  )

  tasks =  completion.choices[0].message["content"]

  print(tasks)

  # tasks = tasks.replace("```", "").replace("\n", "").replace("\\", "").replace('json', '')

  # tasks = tasks[:tasks.rfind('}') + 1]
  

  return tasks


if __name__ == "__main__":

  file = open('./test/test.txt', 'r', encoding="utf-8")

  tasks = getTaskList(file.read(), 'Nov. 4, 2023', 'Dec. 7, 2023')

  print(tasks)

  
